name: Onboarding to the Data Community of Practice
description: Use this template when joining the "Data Nerds" community of practice to get a checklist of tasks to self-onboard.
title:  "{Name}: Onboarding Tasks "
labels: [ "data-nerds",]
assignees:
  - octocat
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: This is just a placeholder for now
      placeholder:
      value:
    validations:
      required: false
