name: Add to project
on:
  issues:
    types:
      - opened
      - labeled
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'contributors profile'
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/open-austin/projects/10
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}